#!/usr/bin/env php
<?php
if ($argc < 2) {
    die('Unable to commence, Service namespace is missing. ' . PHP_EOL . 'Please define the namespace (<company>\<project>');
}
$nameSpace = $argv[1];
if (in_array($nameSpace, ['--help','-h', '-?', '--h','--?', '-help'])) {
    die(<<<HELP
Required: The first argument is the namespace <company>\<project>
Optional: The second argument is the host:port combo. Default is 0.0.0.0:0.
            If the default is provided, a random port will be selected.
            If 127.0.0.1 is specified, the service will only respond to
            local requests.
            If only a port is specified, 127.0.0.1 will be used.
HELP
);
}

$argv[0] = array_shift($argv);

$autoLoadPath = [
    [__DIR__ . '/../../autoload.php', __DIR__ . '/src/ReactServer.php' ],
    [__DIR__ . '/../vendor/autoload.php', __DIR__ . '/src/ReactServer.php'],
    [__DIR__ . '/vendor/autoload.php', __DIR__ . '/src/ReactServer.php']
];

foreach ($autoLoadPath as $paths) {
    if (file_exists($paths[0])) {
        define('COMPOSER_AUTOLOADER', $paths[0]);
        define('REACT_SERVER_INSTALL', $paths[1]);
        break;

    }
}
unset($autoLoadPath);
unset($paths);

if (!defined('COMPOSER_AUTOLOADER')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require COMPOSER_AUTOLOADER;

$routerClass = '\\'.$nameSpace . '\\' . 'Router';

if (!class_exists($routerClass,true)) {
    die('Unable to find the router ('.$routerClass.')');
} else {
    $router = new $routerClass();
}

require REACT_SERVER_INSTALL;



/**
Including this in the file, as the idea came from phpunit...

PHPUnit

Copyright (c) 2001-2017, Sebastian Bergmann <sebastian@phpunit.de>.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in
   the documentation and/or other materials provided with the
   distribution.

 * Neither the name of Sebastian Bergmann nor the names of his
   contributors may be used to endorse or promote products derived
   from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.

*/